import Sidebar from "@/components/Sidebar";
import "../styles/index.css";
import cn from "classnames";
import { Inter, DM_Sans, Poppins } from "next/font/google";
import { socials } from "@/mocks/socials";
import { links } from "@/mocks/links";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

const dmSans = DM_Sans({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
  variable: "--font-dm-sans",
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
  variable: "--font-poppins",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>Dazal Design Studio</title>
        <meta name="description" content="Personal template for creators." />
      </head>
      <body className={cn(inter.variable, poppins.variable, dmSans.variable)}>
        <main
          style={{
            display: "flex",
          }}
        >
          <Sidebar links={links} socials={socials} />
          {children}
        </main>
      </body>
    </html>
  );
}
